### ISSUE TITLE
The Network Type Setting sometimes might reset after switching SIM / Airplane Mode, etc

### ISSUE THREAD

**Issue by cyfung1031** [yunus-ceyhan/Hidden-Settings#1]
Hi,

I like your apps. @yunus-ceyhan 

However, it seems that Xiaomi smartphone cannot really remember the Network Type Setting.
I am not sure how to reproduce, but it does reset, and lose the 5G setting.

I want to have a button so that I do not need to click Phone Info -> Wait Phone Info -> Click Phone 0 -> Wait Phone Info -> Set NR/LTE -> Wait -> Click Phone 1 -> Wait -> Set NR/LTE -> Exit App

OR it would be great that, the application itself can remember my last preferred setting, and it can automatically detect 
(both SIM1 & SIM2) and set it back if the system does not remember my preference.

**Comment by yunus-ceyhan** [comment]
Hi @cyfung1031  

Hidden Settings is only a shortcut application that lets you access some device settings hidden by the manufacturer. It neither has access to change system settings nor has any impact on it. Even with root access that may be challenging. You may check Magisk modules for that purpose if your device has root access already.
