### ISSUE TITLE
Premium not active?

### ISSUE THREAD

**Issue by SEAL300** [yunus-ceyhan/Hidden-Settings#4]
![Screenshot_2024-12-19-17-00-28-048_com android vending](https://github.com/user-attachments/assets/bc1e6e51-31cd-4c28-bc0b-a61df7f9db2f)
I already have bought premium and even can't restore 
![Screenshot_2024-12-19-17-03-21-924_com ceyhan sets](https://github.com/user-attachments/assets/0aaa0ce0-2e76-4028-a8c2-17fbe3bf8e01)
my purchase!

**Comment by yunus-ceyhan** [comment]
So you are premium now, what's the problem then?

19 Ara 2024 Per 17:04 tarihinde SEAL300 ***@***.***> şunu
yazdı:

**Comment by SEAL300** [comment]
I get premium eventually but I thought it would let me get the shortcut in the quick tiles but it didn't so the app doesn't work for me ,and google denied my refund 😅

**Comment by SEAL300** [comment]
Hey man if is there anything we could do there is my email bishoy3012@gmail.com

**Comment by yunus-ceyhan** [comment]
> I get premium eventually but I thought it would let me get the shortcut in the quick tiles but it didn't so the app doesn't work for me ,and google denied my refund 😅

I will look for that feature; if possible, I will consider it. I can refund you, just give me your order number

**Comment by SEAL300** [comment]
GPA.3316-3783-7382-50650
Thanks man much appreciated,if the app get this feature I will surely get premium ☺️🙏

**Comment by yunus-ceyhan** [comment]
Your refund has been made. Thanks for your feedback.
